nav:
  blog: /
  works: https://scottcazan.com/works
  events: https://scottcazan.com/events
  about: https://scottcazan.com/about
  scottcazan.com: https://scottcazan.com

projects_url: http://github.com/scazan

customize:
    gravatar:
        email: 
    logo:
        enabled: false
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        gravatar: false
      android:
        gravator: false
      apple:
        gravator: false
    social_links:
        github: http://github.com/scazan
        instagram: http://instagram.com/scazan
        twitter: http://twitter.com/scazan
    show_all_posts: false
    post_count: 10
    highlight: pojoaque

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-23356250-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
